service: arbiluna

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  cronHandler:
    handler: src/handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
